[project]
name = "emotion-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
    "opencv-python-headless<5",
    "pillow>=12.3.0",
    "streamlit>=1.64.0",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]
